# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from teensy/teensy_angles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class teensy_angles(genpy.Message):
  _md5sum = "ff3325ea44ea22847dec9013538e06aa"
  _type = "teensy/teensy_angles"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 j1_angle
float64 j2_angle
float64 j3_angle
float64 j4_angle
float64 j5_angle
float64 j6_angle
"""
  __slots__ = ['j1_angle','j2_angle','j3_angle','j4_angle','j5_angle','j6_angle']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       j1_angle,j2_angle,j3_angle,j4_angle,j5_angle,j6_angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(teensy_angles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.j1_angle is None:
        self.j1_angle = 0.
      if self.j2_angle is None:
        self.j2_angle = 0.
      if self.j3_angle is None:
        self.j3_angle = 0.
      if self.j4_angle is None:
        self.j4_angle = 0.
      if self.j5_angle is None:
        self.j5_angle = 0.
      if self.j6_angle is None:
        self.j6_angle = 0.
    else:
      self.j1_angle = 0.
      self.j2_angle = 0.
      self.j3_angle = 0.
      self.j4_angle = 0.
      self.j5_angle = 0.
      self.j6_angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.j1_angle, _x.j2_angle, _x.j3_angle, _x.j4_angle, _x.j5_angle, _x.j6_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.j1_angle, _x.j2_angle, _x.j3_angle, _x.j4_angle, _x.j5_angle, _x.j6_angle,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.j1_angle, _x.j2_angle, _x.j3_angle, _x.j4_angle, _x.j5_angle, _x.j6_angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.j1_angle, _x.j2_angle, _x.j3_angle, _x.j4_angle, _x.j5_angle, _x.j6_angle,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
